tiktok/sparo

apps/sparo-lib/src/services/GitSparseCheckoutService.ts, common/changes/sparo/fix-log-format_2024-02-22-02-44.json
=> Fix log format

apps/sparo-lib/src/services/SparoProfileService.ts, common/changes/sparo/fix-fix_sparse_service_load_path_2024-02-22-10-08.json
Fix load path in `SparoProfileService`. 
If execute sparo inside a nested folder, sparo will throw errors like 
This PR fixes this error by using `path.resolve` and calculate absolute path of sparo profiles folder with `repoRoot`
=> fix: fix sparo profile load path in SparoProfileService

apps/sparo-lib/src/cli/commands/checkout.ts, apps/sparo-lib/src/services/SparoProfileService.ts, common/changes/sparo/fix-checkout-uncommitted-sparo-profile_2024-02-22-22-26.json
Supports checkout to uncommitted sparo profile.
Local
=> Fix checkout uncommitted sparo profile

apps/sparo-lib/package.json, apps/sparo-lib/src/cli/SparoCICommandLine.ts, apps/sparo-lib/src/cli/SparoCommandLine.ts, apps/sparo-lib/src/cli/SparoStartupBanner.ts, apps/sparo-lib/src/di/container.ts, apps/sparo-lib/src/logic/GitVersionCompatibility.ts, apps/sparo-lib/src/logic/SparoVersion.ts, apps/sparo-lib/src/services/ArgvService.ts, apps/sparo-lib/src/services/TerminalService.ts, common/changes/sparo/main_2024-02-23-01-27.json, common/config/rush/pnpm-lock.yaml
Add a startup banner display version infos.
=> Feat startup banner

apps/sparo-lib/assets/sparo-profile.json, apps/sparo-lib/src/cli/commands/cmd-list.ts, apps/sparo-lib/src/cli/commands/init-profile.ts, apps/sparo-lib/src/cli/commands/util.ts, apps/sparo-lib/src/services/SparoProfileService.ts, apps/website/docs/pages/commands/overview.md, common/changes/sparo/feat-init-profile_2024-02-23-19-26.json
Add "sparo init-project --profile <name>" command
Local
=> Feat init profile

apps/website/README.md, apps/website/docusaurus.config.js, apps/website/package.json, common/config/rush/pnpm-config.json, common/config/rush/pnpm-lock.yaml
Add a search box.  Since our site is currently small, I avoided a server dependency by using a plugin for [Lunr.js](https://lunrjs.com/) that downloads the search index from the CDN and performs search using JavaScript.
=> Website: Enable search box

apps/sparo-lib/src/cli/commands/clone.ts, apps/sparo-lib/src/services/GitCloneService.ts, common/changes/sparo/main_2024-02-28-16-29.json
=> chore: support for cloning a specify branch

apps/sparo-lib/src/services/GitSparseCheckoutService.ts, common/changes/sparo/feat-improve-checkout-error-log_2024-02-29-22-00.json
Improve error log when profile is selecting a tag specified with no projects.
=> feat: improve error logs when running rush list failed

apps/sparo-lib/src/services/SparoProfileService.ts, common/changes/sparo/feat-improve-load-profiles_2024-03-01-21-11.json
Allow other configuration files (such as OWNERS) under sparo-profiles folder.
Local
=> Feat improve load profiles

apps/sparo-lib/src/cli/commands/checkout.ts, apps/sparo-lib/src/cli/commands/clone.ts, apps/sparo-lib/src/cli/commands/cmd-list.ts, apps/sparo-lib/src/cli/commands/list-profiles.ts, apps/sparo-lib/src/cli/commands/pull.ts, apps/sparo-lib/src/services/GitSparseCheckoutService.ts, apps/sparo-lib/src/services/SparoProfileService.ts, common/changes/sparo/feat-support_profile_parameters_in_pull_2024-02-28-12-40.json
Support profile related parameters in pull & clone command
* add function `ensureSkeletonExistAndUpdated` in `GitSparseCheckoutService`  to avoid duplicated initialization for skeleton.
* add new pull command in sparo with profile related parameters support.
* add profile related parameters support in clone command.
* `resolveSparoProfileAsync` function was moved to `SparoProfileService`
* add `preprocessProfileArgs` and `syncProfileState` in `SparoProfileService` for code sharing. 
Notice:
Unlike `sparo checkout` command, clone and pull command will invoke native git command first and try to get profile in local file system.
Manually tested.
=> feat: support profile parameters in pull & clone command

apps/sparo-lib/src/cli/commands/clone.ts, apps/sparo-lib/src/cli/commands/init-profile.ts, apps/sparo-lib/src/services/GitSparseCheckoutService.ts, apps/sparo-lib/src/services/SparoProfileService.ts, common/changes/sparo/feat-support_profile_parameters_in_pull_2024-02-28-12-40.json, common/changes/sparo/tweak-1_2024-03-05-04-01.json
1. Remove `--add-profile` in `sparo clone`
2. Improve help text for "sparo init-profile"
3. Improve logs in "syncProfileState" function
=> chore: final tweak before 1.0

apps/sparo-lib/src/services/SparoProfileService.ts, common/changes/sparo/main_2024-03-05-03-36.json
Since it has already been determined whether it is a JSON file before calling the `_getProfileName` function, there is no need for a secondary verification here
=> chore: use path.parse instead of split

apps/sparo-lib/src/services/GitSparseCheckoutService.ts, common/changes/sparo/fix-find-plugin-paths_2024-03-08-23-42.json
Fix the find plugin paths logic under a subfolder of repository.
Local
=> Fix find plugin paths

common/scripts/install-run-rush-pnpm.js, common/scripts/install-run-rush.js, common/scripts/install-run-rushx.js, common/scripts/install-run.js, rush.json
Upgrade rush.js to 5.120.2
[Node security issue](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2#command-injection-via-args-parameter-of-child_processspawn-without-shell-option-enabled-on-windows-cve-2024-27980---high)
https://github.com/microsoft/rushstack/pull/4637
=> chore: upgrade rush.js to fix Node.js CVE-2024-27980 security issue

apps/sparo-lib/src/cli/SparoCICommandLine.ts, apps/sparo-lib/src/cli/SparoCommandLine.ts, apps/sparo-lib/src/cli/commands/checkout.ts, apps/sparo-lib/src/cli/commands/fetch.ts, apps/sparo-lib/src/services/GitService.ts, apps/sparo-lib/src/services/GracefulShutdownService.ts, common/changes/sparo/feat-fetch-all_2024-04-12-21-23.json, common/changes/sparo/feat-fetch-all_2024-04-12-22-38.json, common/reviews/api/sparo-lib.api.md, cspell.config.yaml
1. "sparo fetch --all" temporary turn off single branch mode and fetch all remote branches. This makes 'git branch --remote' works
2. "sparo checkout <branch>" will automatically run "git remote set-branches --add <branch>" once to make "fetch" can fetch those checkout-ed branches.
Local
=> Feat fetch all

apps/sparo-lib/src/cli/commands/checkout.ts, common/changes/sparo/feat-checkout-detched_2024-04-30-17-33.json
Fix error when running "sparo checkout" in a detached HEAD state
`sparo checkout <commit_hash>` can checkout to a detached HEAD state. Running "sparo checkout" again throws error which complains about "Failed to get branch name". This PR fixes this issue to allow "checkout" command in this case.
=> Feat checkout detched

apps/sparo-lib/src/cli/commands/checkout.ts, apps/sparo-lib/src/cli/commands/fetch.ts, common/changes/sparo/feat-improve-necessary-check_2024-05-08-20-27.json
Improve the logic to avoid unnecessary git operations when tracking remote branches.
1. Do not run "git remote set-branches --add" if it's not a single branch mode
2. Do not run the special logic for temporarily turn off single branch mode if it's not a single branch mode.
Local
=> Feat improve necessary check

apps/sparo-lib/src/cli/commands/checkout.ts, apps/sparo-lib/src/services/SparoProfileService.ts, apps/website/docs/pages/commands/sparo_checkout.md, build-tests/sparo-output-test/etc/checkout-help.txt, build-tests/sparo-real-repo-test/etc/checkout-from.txt, build-tests/sparo-real-repo-test/etc/checkout-to.txt, build-tests/sparo-real-repo-test/src/start-test.ts, common/changes/sparo/feat-checkout-to-selector_2024-04-25-14-16.json
Instead of creating Sparo Profiles, sometimes I just want to checkout some projects randomly based on [RushJS selector](https://rushjs.io/pages/developer/selecting_subsets/). 
`sparo checkout --to project-A project-B --from project-C project-D`
=> feat: Sparo checkout support --to/--from option for direct projects selection

apps/sparo-lib/src/cli/commands/checkout.ts, apps/sparo-lib/src/cli/commands/fetch.ts, apps/sparo-lib/src/cli/commands/pull.ts, apps/sparo-lib/src/services/GitRemoteFetchConfigService.ts, apps/sparo-lib/src/services/GitService.ts, apps/sparo-lib/src/services/test/GitRemoteFetchConfigService.test.ts, build-tests/sparo-output-test/etc/top-level-help.txt, common/changes/sparo/feat-pull-remote-fetch_2024-05-24-00-11.json, common/reviews/api/sparo-lib.api.md
`sparo fetch` and `sparo pull` automatically clean up merged branches from the git configuration before actually invoking git fetch or pull
Assuming "nonexistent" branch is tracking in the git configuration. Before "sparo fetch" calls the actual "git fetch" command, it will automatically check the existence of the branch in remote, and remove it from the git configuration if it doesn't exist remotely, such as it has been merged into the main branch.
Local
=> Feat pull remote fetch

apps/sparo-lib/src/cli/commands/pull.ts, common/changes/sparo/fix-sparo-pull-with-selectors_2024-05-29-01-26.json
=> fix: sparo pull need to track rush selectors also

apps/sparo-lib/src/cli/commands/checkout.ts, apps/sparo-lib/src/services/GitService.ts, common/changes/sparo/feat-checkout-dash_2024-05-30-05-28.json, common/reviews/api/sparo-lib.api.md
Previously, "sparo checkout" throws an error when parsing "-" branch name. Now "sparo checkoout -" can work similiar to "git checkout -" does
When parsing "-" branch, sparo reads the logs from `.git/logs/HEAD` from and get the previous branch name. With this branch name, do the following logic as normal.
Local
=> Supports "sparo checkout -"

apps/sparo-lib/src/services/CommandService.ts, apps/sparo-lib/src/services/GitRemoteFetchConfigService.ts, apps/sparo-lib/src/services/GitService.ts, apps/sparo-lib/src/services/TerminalService.ts, common/changes/sparo/feat-sparo-metric_2024-06-27-23-23.json, common/changes/sparo/feat-sparo-metric_2024-06-27-23-46.json, common/reviews/api/sparo-lib.api.md
1. Improve the logic to check existence of a branch
2. Improve the logic to accurately report success data
1. `git ls-remote --exist-code` explicitly returns exit code 2 to indicate the branch is missing remotely. The new logic respects this logic, that says other exit code will be treated the branch exists remotely.
2. Previously, all data are sent via telemetry service. After this PR, data will be sent only for success commands.
Local
=> Feat sparo metric

apps/sparo-lib/src/cli/commands/clone.ts, common/changes/sparo/feat-clone-full_2024-07-11-21-24.json
Automatically set up recommended git configuration even when full clone
=> Automatically set up recommended git configuration even when full clone

apps/sparo-lib/src/cli/commands/fetch.ts, common/changes/sparo/feat-fetch-behavior_2024-07-11-22-08.json
"sparo fetch" behaves the same as "git fetch" when no remote or no branches specified
Right now, `sparo fetch origin` will be treated as `git fetch origin <current_branch>`. This doesn't follow the same behavior as `git fetch` does. This PR fixes it and get aligned with `git fetch`
=> "sparo fetch" behaves the same as "git fetch" when no remote or no branches specified

common/config/rush/pnpm-config.json, common/config/rush/pnpm-lock.yaml, common/pnpm-patches/lunr@2.3.9.patch
Patch `lunr.utils.warn` to use `console.log` instead of `console.warn`
Lunr prints error message with `console.warn` which print on stderr. The messages are treated as error message by `rush build`
After patching the code of lunr, it uses `console.log` to print the message.
Local
=> fix: website build

apps/sparo-lib/src/cli/commands/checkout.ts, apps/sparo-lib/src/services/GitRemoteFetchConfigService.ts, common/changes/sparo/fix-branch-fetch-config_2024-09-23-22-33.json
Fix git configurations for tracking branch
Because of single branch mode, we need to put extra efforts on git configuration for feature branches. `branch.<branch>.remote` and `branch.<branch>.merge` was reported missing in user enviornment. This MR takes care of these two git configurations when checking out branches.
Tested locally
=> Fix branch fetch config

apps/sparo-lib/src/services/GitService.ts, common/changes/sparo/fix-exact-pattern_2025-03-18-20-55.json
When checking for the existence of a remote branch, `git ls-remote` uses a [glob pattern](https://git-scm.com/docs/git-ls-remote) to filter all matched remote branches. 
This can sometimes produce incorrect results. For example, checking for `refs/heads/test` with the pattern test will also match the branch `refs/heads/others/test`.
=> fix: use more accurate pattern when checking remote branch existence
