.github/workflows/main.yml
.github/workflows/publish.yaml
common/config/rush/.npmrc-publish
common/config/rush/command-line.json
common/config/rush/version-policies.json
rush.json

Set up release pipeline and prepare for the first release.

Release setup

---

README.md
apps/sparo-lib/README.md
apps/sparo/README.md
common/changes/sparo/octogonz-alpha-disclaimer_2024-02-22-00-53.json

Update README.md files to add a notice clarifying that the software is not yet ready for general usage.

Add README.md disclaimers

---

apps/website/build.js
apps/website/package.json

We weren't running `docusaurus build` during CI

Fix an issue where the website project did not get built by CI

---

apps/sparo-lib/package.json
apps/sparo-lib/src/cli/SparoStartupBanner.ts
apps/sparo/README.md
apps/sparo/package.json
common/changes/sparo/octogonz-website-links_2024-02-27-06-24.json

Now that the website is live, add some links in the package docs.

Add website links to README.md and package.json

---

apps/sparo-lib/.vscode/launch.json
apps/sparo-lib/package.json
apps/sparo-lib/src/api/Sparo.ts
apps/sparo-lib/src/cli/SparoCICommandLine.ts
apps/sparo-lib/src/cli/SparoCommandLine.ts
apps/sparo-lib/src/cli/SparoStartupBanner.ts
apps/sparo-lib/src/index.ts
apps/sparo-lib/src/logic/SparoLibPackage.ts
apps/sparo/package.json
apps/sparo/src/SparoCommandSelector.ts
apps/sparo/src/SparoPackage.ts
common/changes/sparo/feat-update-notifier_2024-02-26-23-56.json
common/config/rush/pnpm-lock.yaml
common/reviews/api/sparo-lib.api.md

Feat update notifier

---

apps/sparo-lib/src/cli/commands/checkout.ts
apps/sparo-lib/src/cli/commands/git-checkout.ts
apps/sparo-lib/src/cli/commands/git-clone.ts
apps/sparo-lib/src/cli/commands/git-fetch.ts
apps/sparo-lib/src/cli/commands/git-pull.ts
apps/sparo-lib/src/cli/commands/help.ts
apps/sparo-lib/src/cli/commands/init-profile.ts
apps/sparo-lib/src/services/ArgvService.ts
common/changes/sparo/feat-help_2024-02-28-00-03.json

feat: show help text

---

apps/sparo-lib/src/services/GitSparseCheckoutService.ts
common/changes/sparo/feat-subspace-skeleton_2024-03-01-00-52.json

feat: add <project_folder>/subspace folder into skeleton

---

apps/sparo-lib/src/services/GitSparseCheckoutService.ts
common/changes/sparo/fix-error-message_2024-03-01-22-04.json

Fix error message

---

apps/sparo-lib/src/cli/commands/checkout.ts
common/changes/sparo/fix-checkout_2024-03-02-04-33.json

Fix the set profile logic in "sparo checkout"

Fix checkout

---

apps/website/config/rush-project.json
common/config/rush/build-cache.json

1. turn on local build cache
2. configure dist folders of build phase for website project

Feat enable local build cache

---

apps/sparo-lib/src/services/SparoProfileService.ts
common/changes/sparo/main_2024-03-04-23-35.json

fix: compatible with windows

---

README.md
apps/sparo-lib/README.md
apps/sparo/README.md
apps/website/docs/pages/guide/getting_started.md
common/changes/sparo/octogonz-under-construction_2024-03-05-00-38.json

Remove "under construction" notices

---

apps/sparo-lib/assets/sparo-profile.json
apps/sparo-lib/src/schemas/sparo-profile.schema.json
apps/sparo/README.md
apps/website/docs/pages/configs/profile_json.md
apps/website/docs/pages/guide/sparo_profiles.md
apps/website/docusaurus.config.js
apps/website/static/schemas/sparo-profile.schema.json
common/changes/sparo/octogonz-website-fixes2_2024-03-05-06-29.json

I also improved the schema docs.

Publish sparo-profile.schema.json on the website

---

apps/sparo/README.md
apps/website/docs/index.md
apps/website/docs/pages/commands/sparo_auto-config.md
apps/website/docs/pages/commands/sparo_checkout.md
apps/website/docs/pages/commands/sparo_clone.md
apps/website/docs/pages/commands/sparo_fetch.md
apps/website/docs/pages/commands/sparo_init-profile.md
apps/website/docs/pages/commands/sparo_list-profiles.md
apps/website/docs/pages/guide/getting_started.md
apps/website/docs/pages/guide/sparo_profiles.md
apps/website/docs/pages/support/help.md
apps/website/docs/pages/support/news.md
common/changes/sparo/octogonz-website-content_2024-03-05-07-55.json

I updated the tutorials to include `sparo init-profile` and did another round of editing.

Documentation updates

---

apps/sparo-lib/src/cli/SparoStartupBanner.ts
common/changes/sparo/fix-version_2024-03-06-01-44.json

Fix version

---

.github/workflows/ci.yml
apps/sparo-lib/src/services/ArgvService.ts
build-tests/sparo-output-test/etc/checkout-help.txt
build-tests/sparo-output-test/etc/clone-help.txt
build-tests/sparo-output-test/etc/top-level-help.txt
common/changes/sparo/fix-sparo-commit_2024-03-09-02-27.json

Fix sparo commit

---

common/config/rush/command-line.json

Enable watch mode in sparo repo

chore: enable watch mode for developing

---

apps/sparo-lib/src/api/Sparo.ts
apps/sparo-lib/src/cli/SparoCICommandLine.ts
apps/sparo-lib/src/cli/SparoCommandLine.ts
apps/sparo-lib/src/services/GitSparseCheckoutService.ts
common/changes/sparo/feat-extended-skeleton_2024-03-13-20-23.json
common/reviews/api/sparo-lib.api.md

Add an "extendedSkeletonFolders" launch option, it accepts a list of project folders and will be added to skeleton folders.
Local

Feat extended skeleton

---

apps/sparo-lib/assets/sparo-profile.json
apps/sparo-lib/src/schemas/sparo-profile.schema.json
apps/website/docs/pages/configs/profile_json.md
apps/website/static/schemas/sparo-profile.schema.json
common/changes/sparo/chore-update-sparo-profile-template_2024-03-14-23-58.json

1. Add comment for tag concept
2. Add comment for folder paths defined in "includeFolders" and "excludedFolders"

Chore update sparo profile template

---

apps/sparo-lib/src/cli/commands/checkout.ts
apps/sparo-lib/src/index.ts
apps/sparo-lib/src/services/ArgvService.ts
apps/sparo-lib/src/services/GitService.ts
apps/sparo-lib/src/services/test/GitService.test.ts
common/changes/sparo/feat-sparo-checkout_2024-03-26-22-11.json
common/reviews/api/sparo-lib.api.md

Make `sparo checkout` work with branch, tag, commit SHA and file path.
Local

sparo checkout can handle branch, tag, commit SHA and file path

---

zsh-plugin/sparo/README.md
zsh-plugin/sparo/install.sh
zsh-plugin/sparo/sparo.plugin.zsh

This PR adds a sparo zsh plugin.

sparo zsh plugin

---

apps/sparo-lib/src/cli/commands/cmd-list.ts
apps/sparo-lib/src/cli/commands/pull.ts
apps/sparo-lib/src/logic/LocalState.ts
apps/website/docs/pages/commands/overview.md
apps/website/docs/pages/commands/sparo_git-pull.md
apps/website/docs/pages/commands/sparo_pull.md
apps/website/sidebars.js
build-tests/sparo-output-test/etc/top-level-help.txt
common/changes/sparo/feat-sparo-pull_2024-04-09-23-05.json

Add "sparo pull"
"sparo pull" internally run `git pull` and sync up the sparse checkout-ed folders accordingly.
Local

Feat sparo pull

---

apps/sparo-lib/src/services/SparoProfileService.ts
common/changes/sparo/fix-dedup-temporary-selections_2024-05-10-00-44.json

Fix dedup temporary selections

---

apps/sparo-lib/src/cli/commands/checkout.ts
apps/website/docs/pages/commands/sparo_checkout.md
build-tests/sparo-output-test/etc/checkout-help.txt
common/changes/sparo/feat-no-profile-help_2024-05-24-21-14.json

Improve "sparo checkout" help text
Local

Feat no profile help

---

apps/sparo-lib/src/cli/commands/pull.ts
common/changes/sparo/fix-failed-pull_2024-07-11-21-41.json

Print error message and exit when git pull fails

Print error message and exit when git pull fails

---

apps/sparo-lib/src/services/ArgvService.ts
apps/website/build.js
build-tests/sparo-completion-test/etc/sparo-top-level-2-completion.txt
build-tests/sparo-completion-test/src/start-test.ts
common/changes/sparo/fix-completion_2024-08-27-05-07.json

Fix an issue with Sparo shell completion
Top level command, i.e. "sparo ", completion doesn't work
Added a build test case

Fix completion

---

.github/workflows/website-deploy.yaml

feat: deploy website can be manuall triggered

---

.github/workflows/sparo-gh-release.yaml
.gitignore
common/autoinstallers/generate-release-description/generate.js
common/autoinstallers/generate-release-description/index.js
common/autoinstallers/generate-release-description/package.json
common/autoinstallers/generate-release-description/pnpm-lock.yaml
common/config/rush/command-line.json

chore: sparo github release

---

apps/sparo-lib/src/services/GitSparseCheckoutService.ts
common/changes/sparo/improve-log_2024-10-23-17-46.json

Fixes https://github.com/tiktok/sparo/issues/92
Improve log to print both stdout and stderr

Improve log

---

common/config/rush/version-policies.json

chore: prepare next minor version

---

.github/workflows/ci.yml

Update the CI token
